# Generated by Django 3.0.7 on 2020-07-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_todo',
        ),
    ]
