# Generated by Django 3.0.7 on 2020-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_date_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_todo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
