# Generated by Django 3.0.7 on 2020-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200809_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='', upload_to='todopics'),
            preserve_default=False,
        ),
    ]
