# Generated by Django 3.0.7 on 2020-08-11 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200809_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='decription',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
