# Generated by Django 3.0.7 on 2020-08-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200811_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
