# Generated by Django 3.0.7 on 2020-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200811_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.CharField(choices=[('computer', 'computer'), ('books', 'books'), ('Furniture', 'Furniture')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
