# Generated by Django 3.0.7 on 2020-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.CharField(choices=[('computer', 'computer'), ('books', 'books'), ('furniture', 'furniture')], max_length=10),
        ),
    ]
